version: "3.8"
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Kiani4030!"
      MSSSQL_PID: "Express"
    ports:
      - "1433:1433"
      